# Generated by Django 3.2.5 on 2021-07-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_movie_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='movie-pics'),
        ),
    ]
