# Generated by Django 3.2.5 on 2021-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210729_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Drama', 'Drama')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='movie-pics'),
        ),
    ]
