# Generated by Django 3.2.5 on 2021-08-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Drama', 'Drama'), ('Adventure', 'Adventure'), ('Sci-Fi', 'SciFi'), ('Crime', 'Crime')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.movie')),
            ],
        ),
    ]
