# Generated by Django 3.2.5 on 2021-08-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210805_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='movie',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie',
            field=models.ManyToManyField(null=True, to='blog.Movie'),
        ),
    ]
