# Generated by Django 3.2.5 on 2021-08-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_alter_watchlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='user_id',
            field=models.OneToOneField(default='No Movies', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
