# Generated by Django 3.2.5 on 2021-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='lastName',
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
