# Generated by Django 3.2.5 on 2021-08-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210810_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.movie'),
        ),
    ]
