# Generated by Django 3.2.5 on 2021-08-10 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 10, 11, 37, 57, 320571)),
        ),
    ]
