# Generated by Django 3.2.5 on 2021-08-13 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mean_rating',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 13, 16, 53, 26, 732783)),
        ),
    ]
