# Generated by Django 3.2.5 on 2021-08-13 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210813_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mean_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 8, 13, 17, 36, 32, 495545)),
        ),
    ]
